package migrations

import (
	"fmt"

	"gorm.io/gorm"
)

// cleanupOrphanedConstraints pre-creates orphaned constraints that GORM will try to DROP
// without IF EXISTS during AutoMigrate. By ensuring they exist beforehand, the DROP succeeds cleanly.
func cleanupOrphanedConstraints(db *gorm.DB) {
	_ = db.Exec(`
		DO $$
		BEGIN
			IF EXISTS (
				SELECT 1 FROM information_schema.columns
				WHERE table_schema = 'administrative'
				  AND table_name = 'companies'
				  AND column_name = 'codigo_empresa'
			) THEN
				IF NOT EXISTS (
					SELECT 1 FROM information_schema.table_constraints
					WHERE table_schema = 'administrative'
					  AND table_name = 'companies'
					  AND constraint_name = 'uni_companies_codigo_empresa'
				) THEN
					BEGIN
						ALTER TABLE administrative.companies ADD CONSTRAINT uni_companies_codigo_empresa UNIQUE (codigo_empresa);
					EXCEPTION WHEN OTHERS THEN
						NULL;
					END;
				END IF;
			END IF;
		END $$;
	`)
}

// Migrate runs GORM AutoMigrate for the provided models after ensuring the required schema exists.
func Migrate(db *gorm.DB, models ...interface{}) error {
	// Create administrative schema if not exists
	if err := db.Exec("CREATE SCHEMA IF NOT EXISTS administrative").Error; err != nil {
		return fmt.Errorf("failed to create schema administrative: %w", err)
	}
	// Create app schema if not exists
	if err := db.Exec("CREATE SCHEMA IF NOT EXISTS app").Error; err != nil {
		return fmt.Errorf("failed to create schema app: %w", err)
	}

	cleanupOrphanedConstraints(db)

	if err := db.AutoMigrate(models...); err != nil {
		return err
	}

	// Create CHECK constraints and composite indexes for the referido table.
	// These cannot be generated by GORM's AutoMigrate.
	referidoConstraints := []string{
		`DO $$ BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'referido'
				  AND constraint_name = 'chk_referido_estado'
			) THEN
				ALTER TABLE administrative.referido
				ADD CONSTRAINT chk_referido_estado
				CHECK (estado IN ('pendiente', 'registrado', 'afiliado'));
			END IF;
		END $$`,
		`DO $$ BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'referido'
				  AND constraint_name = 'chk_referido_no_auto_referencia'
			) THEN
				ALTER TABLE administrative.referido
				ADD CONSTRAINT chk_referido_no_auto_referencia
				CHECK (usuario_referente_id <> usuario_referido_id);
			END IF;
		END $$`,
	}

	referidoIndexes := []string{
		`CREATE INDEX IF NOT EXISTS idx_referido_estado_recompensa ON administrative.referido (estado, recompensa_otorgada)`,
	}

	for _, stmt := range referidoConstraints {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create referido constraint: %w", err)
		}
	}

	for _, stmt := range referidoIndexes {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create referido index: %w", err)
		}
	}

	// Create CHECK constraints and indexes for the benefit_redemption table.
	redemptionConstraints := []string{
		`DO $$ BEGIN
			IF EXISTS (
				SELECT 1 FROM information_schema.tables
				WHERE table_schema = 'administrative' AND table_name = 'benefit_redemption'
			) THEN
				IF NOT EXISTS (
					SELECT 1 FROM information_schema.table_constraints
					WHERE table_schema = 'administrative'
					  AND table_name = 'benefit_redemption'
					  AND constraint_name = 'chk_redemption_estado'
				) THEN
					ALTER TABLE administrative.benefit_redemption
					ADD CONSTRAINT chk_redemption_estado
					CHECK (estado IN ('generado', 'usado', 'vencido'));
				END IF;
			END IF;
		END $$`,
		`DO $$ BEGIN
			IF EXISTS (
				SELECT 1 FROM information_schema.tables
				WHERE table_schema = 'administrative' AND table_name = 'benefit_redemption'
			) THEN
				IF NOT EXISTS (
					SELECT 1 FROM information_schema.table_constraints
					WHERE table_schema = 'administrative'
					  AND table_name = 'benefit_redemption'
					  AND constraint_name = 'uq_redemption_benefit_usuario'
				) THEN
					ALTER TABLE administrative.benefit_redemption
					ADD CONSTRAINT uq_redemption_benefit_usuario
					UNIQUE (benefit_id, usuario_id);
				END IF;
			END IF;
		END $$`,
	}

	redemptionIndexes := []string{
		`DO $$ BEGIN
			IF EXISTS (
				SELECT 1 FROM information_schema.tables
				WHERE table_schema = 'administrative' AND table_name = 'benefit_redemption'
			) THEN
				CREATE INDEX IF NOT EXISTS idx_redemption_benefit ON administrative.benefit_redemption(benefit_id);
				CREATE INDEX IF NOT EXISTS idx_redemption_usuario ON administrative.benefit_redemption(usuario_id);
			END IF;
		END $$`,
	}

	for _, stmt := range redemptionConstraints {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create benefit_redemption constraint: %w", err)
		}
	}

	for _, stmt := range redemptionIndexes {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create benefit_redemption index: %w", err)
		}
	}

	// Constraints and indexes for membresia and pago_membresia
	membresiaConstraints := []string{
		`DO $$ BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'membresia'
				  AND constraint_name = 'chk_membresia_estado'
			) THEN
				ALTER TABLE administrative.membresia
				ADD CONSTRAINT chk_membresia_estado
				CHECK (estado IN ('inactiva', 'activa', 'vencida', 'cancelada'));
			END IF;
		END $$`,
		`DO $$ BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'pago_membresia'
				  AND constraint_name = 'chk_pago_estado'
			) THEN
				ALTER TABLE administrative.pago_membresia
				ADD CONSTRAINT chk_pago_estado
				CHECK (estado IN ('pendiente', 'aprobado', 'rechazado'));
			END IF;
		END $$`,
		`DO $$ BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'pago_membresia'
				  AND constraint_name = 'chk_pago_tipo'
			) THEN
				ALTER TABLE administrative.pago_membresia
				ADD CONSTRAINT chk_pago_tipo
				CHECK (tipo IN ('inicial', 'renovacion'));
			END IF;
		END $$`,
		`DO $$ BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'companies'
				  AND constraint_name = 'chk_companies_suscripcion_estado'
			) THEN
				ALTER TABLE administrative.companies
				ADD CONSTRAINT chk_companies_suscripcion_estado
				CHECK (suscripcion_estado IN ('prueba', 'activa', 'vencida', 'suspendida'));
			END IF;
		END $$`,
	}

	membresiaIndexes := []string{
		`CREATE INDEX IF NOT EXISTS idx_pago_membresia ON administrative.pago_membresia(membresia_id)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_pago_membresia_referencia_unica ON administrative.pago_membresia(referencia_pasarela) WHERE referencia_pasarela IS NOT NULL`,
	}

	for _, stmt := range membresiaConstraints {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create membresia constraint: %w", err)
		}
	}

	for _, stmt := range membresiaIndexes {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create membresia index: %w", err)
		}
	}

	// Backfill estado='activo' and is_active=true for benefits if null
	_ = db.Exec("UPDATE administrative.benefit SET estado = 'activo' WHERE estado IS NULL OR estado = ''")
	_ = db.Exec("UPDATE administrative.benefit SET is_active = true WHERE is_active IS NULL")

	// Ensure business_validator (role_id 7) has no access to global admin benefits table (menu_id 12)
	_ = db.Exec("DELETE FROM administrative.permissions WHERE role_id = 7 AND menu_id = 12")

	// Backfill user_companies from users.empresa_id for existing validator/negocio users
	_ = db.Exec(`
		INSERT INTO administrative.user_companies (user_id, company_id)
		SELECT id, empresa_id FROM administrative.users
		WHERE empresa_id IS NOT NULL AND empresa_id > 0
		ON CONFLICT DO NOTHING
	`)

	// Clean up any failed or legacy GORM index on nit
	_ = db.Exec("DROP INDEX IF EXISTS administrative.idx_administrative_companies_nit")
	_ = db.Exec("DROP INDEX IF EXISTS administrative.idx_administrative_companies_razon_social")

	// Deduplicate any existing duplicate NITs before creating unique index
	_ = db.Exec(`
		UPDATE administrative.companies c1
		SET nit = c1.nit + c1.id
		WHERE c1.nit IS NOT NULL
		  AND c1.id > (SELECT MIN(c2.id) FROM administrative.companies c2 WHERE c2.nit = c1.nit);
	`)

	// Deduplicate any existing duplicate razon_social before creating unique index
	_ = db.Exec(`
		UPDATE administrative.companies c1
		SET razon_social = c1.razon_social || ' ' || c1.id
		WHERE TRIM(c1.razon_social) <> ''
		  AND c1.id > (SELECT MIN(c2.id) FROM administrative.companies c2 WHERE LOWER(TRIM(c2.razon_social)) = LOWER(TRIM(c1.razon_social)));
	`)

	// Ensure unique index for companies nit (ignoring nulls)
	_ = db.Exec(`
		CREATE UNIQUE INDEX IF NOT EXISTS idx_companies_nit_unique
		ON administrative.companies (nit)
		WHERE nit IS NOT NULL;
	`)

	// Ensure unique index for companies razon_social (ignoring empty strings)
	_ = db.Exec(`
		CREATE UNIQUE INDEX IF NOT EXISTS idx_companies_razon_social_unique
		ON administrative.companies (LOWER(TRIM(razon_social)))
		WHERE razon_social IS NOT NULL AND TRIM(razon_social) <> '';
	`)

	// Ensure unique index for companies name (case-insensitive)
	_ = db.Exec(`
		CREATE UNIQUE INDEX IF NOT EXISTS idx_companies_name_unique
		ON administrative.companies (LOWER(TRIM(name)));
	`)

	// Ensure foreign keys on user_companies cascade on delete so deleting companies or users succeeds cleanly
	_ = db.Exec(`
		DO $$
		BEGIN
			IF EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'user_companies'
				  AND constraint_name = 'fk_administrative_user_companies_company'
			) THEN
				ALTER TABLE administrative.user_companies
				DROP CONSTRAINT fk_administrative_user_companies_company;
			END IF;

			ALTER TABLE administrative.user_companies
			ADD CONSTRAINT fk_administrative_user_companies_company
			FOREIGN KEY (company_id) REFERENCES administrative.companies(id) ON DELETE CASCADE;

			IF EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'user_companies'
				  AND constraint_name = 'fk_administrative_user_companies_user'
			) THEN
				ALTER TABLE administrative.user_companies
				DROP CONSTRAINT fk_administrative_user_companies_user;
			END IF;

			ALTER TABLE administrative.user_companies
			ADD CONSTRAINT fk_administrative_user_companies_user
			FOREIGN KEY (user_id) REFERENCES administrative.users(id) ON DELETE CASCADE;
		EXCEPTION WHEN OTHERS THEN
			NULL;
		END $$;
	`)

	// Create CHECK constraints and indexes for notificaciones
	notifConstraints := []string{
		`DO $$ BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'notificaciones'
				  AND constraint_name = 'chk_notificacion_tipo'
			) THEN
				ALTER TABLE administrative.notificaciones
				ADD CONSTRAINT chk_notificacion_tipo
				CHECK (tipo IN ('pago_membresia_aprobado', 'pago_membresia_rechazado'));
			END IF;
		END $$`,
	}

	notifIndexes := []string{
		`CREATE INDEX IF NOT EXISTS idx_notificaciones_usuario_leido ON administrative.notificaciones (usuario_id, leido)`,
	}

	for _, stmt := range notifConstraints {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create notificaciones constraint: %w", err)
		}
	}
	for _, stmt := range notifIndexes {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create notificaciones index: %w", err)
		}
	}

	// Create CHECK constraints and indexes for password_reset_tokens
	tokenConstraints := []string{
		`DO $$ BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'password_reset_tokens'
				  AND constraint_name = 'chk_password_reset_tokens_tipo'
			) THEN
				ALTER TABLE administrative.password_reset_tokens
				ADD CONSTRAINT chk_password_reset_tokens_tipo
				CHECK (tipo IN ('recuperacion', 'activacion'));
			END IF;
		END $$`,
	}

	tokenIndexes := []string{
		`CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_usuario ON administrative.password_reset_tokens (usuario_id, usado)`,
	}

	for _, stmt := range tokenConstraints {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create password_reset_tokens constraint: %w", err)
		}
	}
	for _, stmt := range tokenIndexes {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create password_reset_tokens index: %w", err)
		}
	}

	// Create table and index for password_reset_code
	codeStatements := []string{
		`CREATE TABLE IF NOT EXISTS administrative.password_reset_code (
			id BIGSERIAL PRIMARY KEY,
			usuario_id BIGINT NOT NULL REFERENCES administrative.users(id),
			codigo_hash VARCHAR(255) NOT NULL,
			intentos_fallidos INT NOT NULL DEFAULT 0,
			usado BOOLEAN NOT NULL DEFAULT false,
			expira_at TIMESTAMPTZ NOT NULL,
			create_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE INDEX IF NOT EXISTS idx_password_reset_code_usuario ON administrative.password_reset_code (usuario_id)`,
	}
	for _, stmt := range codeStatements {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create password_reset_code: %w", err)
		}
	}

	return nil
}
