package migrations

import (
	"fmt"

	"gorm.io/gorm"
)

// cleanupOrphanedConstraints pre-creates orphaned constraints that GORM will try to DROP
// without IF EXISTS during AutoMigrate. By ensuring they exist beforehand, the DROP succeeds cleanly.
func cleanupOrphanedConstraints(db *gorm.DB) {
	// GORM may attempt to drop "uni_companies_nit" if the NIT field was previously tagged
	// with uniqueIndex. We create it if missing so the DROP succeeds, then recreate if needed.
	_ = db.Exec(`
		DO $$
		BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'companies'
				  AND constraint_name = 'uni_companies_nit'
			) THEN
				-- Temporarily create the constraint so GORM can cleanly drop it
				IF EXISTS (
					SELECT 1 FROM information_schema.columns
					WHERE table_schema = 'administrative'
					  AND table_name = 'companies'
					  AND column_name = 'nit'
				) THEN
					EXECUTE 'ALTER TABLE administrative.companies ADD CONSTRAINT uni_companies_nit UNIQUE (nit)';
				END IF;
			END IF;
		END $$;
	`)
}

// Migrate runs GORM AutoMigrate for the provided models after ensuring the required schema exists.
func Migrate(db *gorm.DB, models ...interface{}) error {
	// Create administrative schema if not exists
	if err := db.Exec("CREATE SCHEMA IF NOT EXISTS administrative").Error; err != nil {
		return fmt.Errorf("failed to create schema administrative: %w", err)
	}
	// Create app schema if not exists
	if err := db.Exec("CREATE SCHEMA IF NOT EXISTS app").Error; err != nil {
		return fmt.Errorf("failed to create schema app: %w", err)
	}

	if err := db.AutoMigrate(models...); err != nil {
		return err
	}

	// Create CHECK constraints and composite indexes for the referido table.
	// These cannot be generated by GORM's AutoMigrate.
	referidoConstraints := []string{
		`DO $$ BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'referido'
				  AND constraint_name = 'chk_referido_estado'
			) THEN
				ALTER TABLE administrative.referido
				ADD CONSTRAINT chk_referido_estado
				CHECK (estado IN ('pendiente', 'registrado', 'afiliado'));
			END IF;
		END $$`,
		`DO $$ BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'referido'
				  AND constraint_name = 'chk_referido_no_auto_referencia'
			) THEN
				ALTER TABLE administrative.referido
				ADD CONSTRAINT chk_referido_no_auto_referencia
				CHECK (usuario_referente_id <> usuario_referido_id);
			END IF;
		END $$`,
	}

	referidoIndexes := []string{
		`CREATE INDEX IF NOT EXISTS idx_referido_estado_recompensa ON administrative.referido (estado, recompensa_otorgada)`,
	}

	for _, stmt := range referidoConstraints {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create referido constraint: %w", err)
		}
	}

	for _, stmt := range referidoIndexes {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create referido index: %w", err)
		}
	}

	// Create CHECK constraints and indexes for the benefit_redemption table.
	// The table was created manually in BD — these ensure constraints exist idempotently.
	redemptionConstraints := []string{
		`DO $$ BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'benefit_redemption'
				  AND constraint_name = 'chk_redemption_estado'
			) THEN
				ALTER TABLE administrative.benefit_redemption
				ADD CONSTRAINT chk_redemption_estado
				CHECK (estado IN ('generado', 'usado', 'vencido'));
			END IF;
		END $$`,
		`DO $$ BEGIN
			IF NOT EXISTS (
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_schema = 'administrative'
				  AND table_name = 'benefit_redemption'
				  AND constraint_name = 'uq_redemption_benefit_usuario'
			) THEN
				ALTER TABLE administrative.benefit_redemption
				ADD CONSTRAINT uq_redemption_benefit_usuario
				UNIQUE (benefit_id, usuario_id);
			END IF;
		END $$`,
	}

	redemptionIndexes := []string{
		`CREATE INDEX IF NOT EXISTS idx_redemption_benefit ON administrative.benefit_redemption(benefit_id)`,
		`CREATE INDEX IF NOT EXISTS idx_redemption_usuario ON administrative.benefit_redemption(usuario_id)`,
	}

	for _, stmt := range redemptionConstraints {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create benefit_redemption constraint: %w", err)
		}
	}

	for _, stmt := range redemptionIndexes {
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("failed to create benefit_redemption index: %w", err)
		}
	}

	// Backfill estado='activo' and is_active=true for benefits if null
	_ = db.Exec("UPDATE administrative.benefit SET estado = 'activo' WHERE estado IS NULL OR estado = ''")
	_ = db.Exec("UPDATE administrative.benefit SET is_active = true WHERE is_active IS NULL")

	return nil
}
